### ISSUE TITLE
dispose pattern

### ISSUE THREAD

**Issue by yauhenikh** [epam-lab/dotnet-support-group#2]
В каких конкретно случаях в жизни требуется применять dispose pattern? 

Я уже искал ответ на свой вопрос - да

Я искал ответ на свой вопрос в этих источниках
Например, https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

**Comment by epam-lab** [comment]
Полагаю, что вопрос разворачивается в "когда класс должен реализовывать интерфейс IDisposable?" Если отвечать кратко и только по теме вопроса, то ответ будет следующим - только в двух случаях, когда класс _владеет_ управляемыми и/или неуправляемыми ресурсами.

* Попробуйте начать со статьи ["How to Implement IDisposable and Finalizers: 3 Easy Rules"](https://blog.stephencleary.com/2009/08/how-to-implement-idisposable-and.html).
* После этого реализуйте классический вариант реализации шаблона Dispose для обоих вариантов и изучите поведение шаблона.

Дополнительные материалы по этой теме доступны в разделе [Dispose Pattern](https://github.com/epam-lab/dotnet-support-group/wiki/Reading#dispose-pattern).
