### ISSUE TITLE
Design patterns

### ISSUE THREAD

**Issue by vitalmizevich** [epam-lab/dotnet-support-group#4]
Какое внимание в процессе обучения стоит уделять шаблонам проектирования? Стоит ли сейчас на этом зацикливаться или полное их понимание придет со временем (в частности, возможность реализации "из головы")?

Я уже искал ответ на свой вопрос - да

Я искал ответ на свой вопрос в этих источниках
https://toster.ru/q/425027

**Comment by epam-lab** [comment]
1. Стоит изучить 3-4 простых шаблона, которые часто используются. Например

- Creational (Factory Method, Abstract Factory, Builder)
- Structural (Adapter, Composite, Decorator)
- Behavioral (Chain of Responsibility, Strategy, State, Template Method)

2. Посмотреть, какие шаблоны используются во фреймворке:
https://stackoverflow.com/questions/3252499/what-design-patterns-are-used-throughout-the-net-framework
https://www.slideshare.net/aniruddha.chakrabarti/design-patterns-examples-in-net (есть примеры)

3. Есть неплохая книга - "Шаблоны проектирования. Новый подход к объектно-ориентированному анализу и проектированию". Объясняет некоторые шаблоны на элементарном уровне.

Также см. дополнительные материалы в разделе [Design Patterns](https://github.com/epam-lab/dotnet-support-group/wiki/Reading#design-patterns).

4. Остальные шаблоны лучше изучать или хотя бы бегло просмотреть после того, как появится начальный опыт проектирования программных систем.
