### ISSUE TITLE
EF TPH strategy

### ISSUE THREAD

**Issue by VladKachenya** [epam-lab/dotnet-support-group#7]
Доброго времени суток!
Допустимо ли использовать TPH стратегию обработки иерархии для хранения информации о разных типах товаров (телефон, холодильник, телевизор и т.д.)?
Меня смущает то что при увеличении количества разных типов товаров будет прогрессивно увеличиться количество столбцов таблицы. Рационально ли это?

Я уже искал ответ на свой вопрос - да.

Я искал ответ на свой вопрос в этих источниках:

https://weblogs.thinktecture.com/pawel/2018/05/entity-framework-core-inheritance-tpt-is-not-supported-is-it-part-1-code-first.html
https://blogs.msdn.microsoft.com/alexj/2009/04/14/tip-12-how-to-choose-an-inheritance-strategy/
https://metanit.com/sharp/entityframework/7.1.php
https://metanit.com/sharp/entityframeworkcore/4.1.php

**Comment by epam-lab** [comment]
Вы упомянули стратегию TPH, значит речь идет о наследовании. Также есть разные типы товаров - телефон, холодильник, телевизор, которые по TPH будут находиться в одной таблице, они унаследованы от общего предка, значит ваша иерархия выглядит [следующим образом].(https://www.plantuml.com/plantuml/img/SoWkIImgAStDuUAwCFzYmuLz5xPSRBwmwsAJWasDhgx2XKKNjbxOVM7hnHQWp5xiIfO2HNQ3H2_ikB3xOi-5lK1w5rxJBcm2Ajb-OT_51YukXzIy5A3r0000)

Частые изменения в иерархии, например добавление/удаление наследуемых классов, это признак ошибки в дизайне. Следовательно, изменения в таблице связаны с проблемой дизайна, а не со стратегией EF.

**Comment by VladKachenya** [comment]
Правильно ли я Вас понимаю? TPH подход следует использовать в том случае когда заранее известны все наследники и БД формируется исключительно на этапе проектирования. Соответственно в противном случае, когда требования могут изменятся (например в какой-то момент помимо телефон, холодильник, телевизор понадобится хранить садовые лопаты), следует использовать TPT подход?

**Comment by epam-lab** [comment]
Повторю: "Частые изменения в иерархии, например добавление/удаление наследуемых классов, это признак ошибки в дизайне." Т.е. если вам для хранения садовых лопат нужен новый тип, то нужно посмотреть на дизайн классов, нет ли там ошибки. Например, в вашем случае решением может быть два типа - КатегорияПродукт (который задает принадлежность к определенной группе) и Продукт (в котором есть ссылка на категорию).

**Comment by VladKachenya** [comment]
Наверное я Вас понял. Использовать отдельный класс для описания отдельного типа продукта, в условиях того что таких продуктов может быть много, очень плохо.  Вместо этого нам необходимо иметь таблицу которая описывает товар (общие свойства всех товаров) и отдельную таблицу для хранения свойств и значений этих свойств.

**Comment by epam-lab** [comment]
попробуйте эксперимент: реализуйте оба варианта для 3 товаров, а затем попробуйте добавить новый. потом опишите для обоих случаев, что будет изменятся в базе - новые строки в таблице, новые столбцы, новые таблицы. таким образом вы выясните наиболее оптимальный вариант.

**Comment by VladKachenya** [comment]
Я с Вами согласен. И первый вариант уже попробовал и вот осознал то что он плох тем что придётся каждый раз создавать новый класс и обновлять БД для каждого товара и в зависимости от стратегии будет создаваться новая таблица или расширятся текущая, а также из за того что БД находится в центре приложения, то оно становится очень неповоротливым и закостенелым . По итогу пришёл к выводу что структура БД не должна зависеть от типа товара и для всех типов товаров должен быть определённый набор общих таблиц с описанием этих товаров) В общем надо пробовать второй вариант)
